package Box.math;

public enum BoxMathTokenType {
	PLUS, MINUS, TIMES, POWER, DEVIDE, FUN, DERIVITIVE, DIFFERENTIAL, FACTORIAL, EQUALS, LESSTHENEQUAL, LESSTHEN,
	GREATERTHENEQUAL, GREATERTHEN, SPACE, SPACERETURN, TAB, NEWLINE, STRING, CHAR, IDENTIFIER, NUMBER, LEFT_PAREN,
	RIGHT_PAREN, SIN, COS, TAN, E, LOG, LN, DERIVITIVEVAR, ABS, EOF, YROOT, SINH, COSH, TANH, ASIGNMENTEQUALS, COMMA,
	PI, TODERIVE, INTEGRAL, FROM, TO
}
