package Box.Token;

public enum TokenType implements TokenTypeEnum{
//TokenTypes that have keywords Associated with them
	TRUE,
	EURT,
	FALSE,
	ESLAF,
	PRINT,
	TNIRP,
	RETURN,
	NRUTER,
	SAVE,
	EVAS,
	READ,
	DAER,
	INTO,
	OTNI,
	RENAME,
	EMANER,
	TO,
	OT,
	MOVE,
	EVOM,
	YROOT,
	TOORY,
	SIN,
	NIS,
	COS,
	SOC,
	TAN,
	NAT,
	SINH,
	HNIS,
	COSH,
	HSOC,
	TANH,
	HNAT,
	LOG,
	GOL,
	// rounding / sign
	ABS, SBA,
	SQRT, TRQS,
	FLOOR, ROOLF,
	CEIL, LIEC,
	ROUND, DNUOR,
	SIGN, NGIS,
	// inverse trig
	ASIN, NISA,
	ACOS, SOCA,
	ATAN, NATA,
	ASINH, HNISA,
	ACOSH, HSOCA,
	ATANH, HNATA,
	// two-arg scalar min/max
	MIN, NIM,
	MAX, XAM,
	// three-arg scalar clamp
	CLAMP, PMALC,
	// string ops
	LEN, NEL,
	UPPER, REPPU,
	LOWER, REWOL,
	STRREV, VERUTS,
	TRIM, MIRT,
	NUM, MUN,
	// container aggregates
	SUM, MUS,
	PRODUCT, TCUDORP,
	MEAN, NAEM,
	SORT, TROS,
	MINOF, FONIM,
	MAXOF, FOMAM,
	FIRST, TSRIF,
	LAST, TSAL,
	FLIP, PILF,
	FLAT, TALF,
	// bitwise
	BAND, DNAB,
	BOR, ROB,
	BXOR, ROXB,
	BNOT, TONB,
	BLEFT, TFELB,
	BRIGHT, THGIRB,
	CONTAINS,
	SNIATNOC,
	OPEN,
	NEPO,
	AND,
	DNA,
	OR,
	RO,
	FUN,
	NUF,
	DOUBLE,
	INT,
	BIN,
	NULL,NILL,
	LLUN, LLIN,
	NOT,
	KNOT,
	CUP,
	POCKET,
	BOX,
	
	
	
	
	///userdefined strings ,chars, or numbers
	IDENTIFIER,
	DOUBLENUM,
	INTNUM,
	BINNUM,
	UNKNOWN,
	CHAR, 
	STRING,

	///tokenTypes that have a symbol associated with them
DOT,
COMMA,
ASIGNMENTEQUALS,
EQUALSEQUALS,
EQUALSNOT,
EQUALSPLUS,
EQUALSMINUS,
NOTEQUALS,
PLUSEQUALS,
MINUSEQUALS,
GREATERTHEN,
LESSTHEN,
GREATERTHENEQUAL,
EQUALGREATERTHEN,
LESSTHENEQUAL,
EQUALLESSTHEN,
PLUS,
PLUSPLUS,
MINUS,
MINUSMINUS,
TIMES,
POWER,
BANG,
QMARK,
TEMPLID,
SINGLEAND,
OPENSQUARE,CLOSEDSQUARE,
OPENPAREN,CLOSEDPAREN,
OPENBRACE,CLOSEDBRACE,
FORWARDSLASH,
BACKSLASH,
EXPELL,
CONSUME,
SEMICOLON,
COLON,
DOLLAR,

 


//compound tokens 

BOXCONTAINER,
CUPCONTAINER,
POCKETCONTAINER,
KNOTCONTAINER,

PUPCONTAINER,
COCKETCONTAINER,

LUPCONTAINER,
LOCKETCONTAINER,
LILCONTAINER,

PIDCONTAINER,
CIDCONTAINER,
///end of file


EOF, BOXXX, SPACE, SPACERETURN, TAB, NEWLINE, TONK, PUC, TEKCOP, XOB, EPYT, TYPE, UNDERSCORE, HATTAG , GATTAH, LEFTPAREN, RIGHTPAREN, NUMBER, AT, HASH, MOD, MODEQUAL, TIMESEQUAL, EQUALTIMES, EQUALMOD, EQUALDIVIDEFORWARD, EQUALDIVIDEBACKWARD, EQUALPOWER, POWEREQUAL, PXE, NL, BUS, TATES, HSUP, YTPME, EZIS, RAELC, EVOMER, DDA, EXP, LN, SUB, SETAT, POP, PUSH, EMPTY, SIZE, CLEAR, REMOVE, ADD, TATEG, GETAT, ALIVE, EVILA


//flatlandSpace cmds
,FLMOVE,FLDESTROY,FLCREATE,FLECREATE,FLEDESTROY,FLSETVALUE, RUN, NUR, TON

// math syntax
,DERIVE,EVIRED,INTEGRATE,ETARGETNI,FRESNELS,SLENSREF,FRESNELC,CLENSERF,BY,YB,FROM,MORF,ATKW,TAKW,CONSTANT,TNATSNOC,TARGET,TEGRAT

// assert
,ASSERT,TRESSA

// vector/matrix ops
,NORM,MRON,UNIT,TINU,TRANS,SNART,VDET,TEDV,VINV,VNIV,TRACE,ECART
,VDOT,TODV,CROSS,SSORC,VADD,DDAV,VSUB,BUSV,VSCALE,ELACSV

;


@Override
public Integer returnTokenType(TokenTypeEnum enumToFindOrdinal) {
	
	return null;
}
	

	
	
	
}
